"""Grading for idea items — key-point coverage, not wording.

The owner wants answers graded rather than self-assessed, with a way to push
back when the grading is poor. Two constraints shape the implementation:

1. **No Anthropic API for work material.** Grading runs through the locally
   installed, locally authenticated Claude Code CLI as a subprocess, so
   content never leaves the machine via an API call. That also means grading
   is only available where that CLI exists — the hosted instance falls back.
2. **Never block the loop.** If no grader is available or the call fails, the
   item degrades to learner self-assessment rather than erroring. A review
   session must not depend on a subprocess.

Reference anchors do NOT come through here: they grade deterministically in
:mod:`lms.maintenance.anchors` with no model involved.
"""

from __future__ import annotations

import json
import logging
import shutil
import subprocess
from dataclasses import dataclass
from typing import Any, Protocol

from lms.maintenance.anchors import GradeResult

logger = logging.getLogger(__name__)

CLAUDE_CLI = "claude"
_TIMEOUT_SECONDS = 60


@dataclass(frozen=True)
class KeyPoint:
    """One thing an answer should cover."""

    label: str
    required: bool = True

    @classmethod
    def from_payload(cls, raw: dict[str, Any]) -> KeyPoint:
        return cls(label=str(raw["label"]), required=bool(raw.get("required", True)))


class IdeaGrader(Protocol):
    """Grades a free-text answer against the item's key points."""

    def grade(self, *, prompt: str, answer: str, key_points: list[KeyPoint]) -> GradeResult | None:
        """Return a grade, or None when this grader cannot answer."""


class ClaudeCodeGrader:
    """Grade via the locally installed Claude Code CLI.

    Uses ``claude -p`` (headless print mode) so the call runs under the user's
    own local login. Returns None — never raises — when the CLI is missing,
    times out, or answers unparseably, so the caller can fall back.
    """

    def __init__(self, executable: str = CLAUDE_CLI, timeout: int = _TIMEOUT_SECONDS) -> None:
        self._executable = executable
        self._timeout = timeout

    def available(self) -> bool:
        return shutil.which(self._executable) is not None

    def grade(self, *, prompt: str, answer: str, key_points: list[KeyPoint]) -> GradeResult | None:
        if not self.available():
            return None
        instruction = _build_grading_prompt(prompt=prompt, answer=answer, key_points=key_points)
        try:
            completed = subprocess.run(  # noqa: S603 - fixed executable, no shell
                [self._executable, "-p", instruction],
                capture_output=True,
                text=True,
                timeout=self._timeout,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            logger.warning("idea grading via %s failed; falling back", self._executable)
            return None
        if completed.returncode != 0:
            logger.warning("%s exited %s during grading", self._executable, completed.returncode)
            return None
        return _parse_grade(completed.stdout, key_points)


class KeywordCoverageGrader:
    """Offline fallback: does the answer mention each key point?

    Deliberately crude. It exists so the loop keeps working without a model
    (CI, the hosted instance, an offline laptop) and so tests are
    deterministic — NOT as a serious substitute for judged grading. Its
    explanation says so, because a learner should know when the grade was
    generated by string matching.
    """

    def grade(self, *, prompt: str, answer: str, key_points: list[KeyPoint]) -> GradeResult:
        text = (answer or "").lower()
        hits = [point for point in key_points if _mentions(text, point.label)]
        required = [point for point in key_points if point.required]
        required_hits = [point for point in hits if point.required]
        score = (len(required_hits) / len(required)) if required else float(bool(hits))
        missed = [point.label for point in required if point not in required_hits]
        explanation = (
            f"Keyword check (no grader available): covered {len(required_hits)} of "
            f"{len(required)} required points."
        )
        if missed:
            explanation += " Missed: " + "; ".join(missed) + "."
        return GradeResult(
            score=score,
            passed=score >= 0.6,
            explanation=explanation,
            detail={
                "grader": "keyword-coverage",
                "hit": [p.label for p in hits],
                "missed": missed,
            },
        )


def grade_idea_answer(
    *,
    prompt: str,
    answer: str,
    key_points: list[KeyPoint],
    grader: IdeaGrader | None = None,
) -> GradeResult:
    """Grade an idea answer, degrading gracefully when no grader is available."""
    candidate = grader if grader is not None else ClaudeCodeGrader()
    result = candidate.grade(prompt=prompt, answer=answer, key_points=key_points)
    if result is not None:
        return result
    return KeywordCoverageGrader().grade(prompt=prompt, answer=answer, key_points=key_points)


def _mentions(text: str, label: str) -> bool:
    """Loose containment check on the label's distinctive words."""
    words = [w for w in label.lower().replace("/", " ").split() if len(w) > 3]
    if not words:
        return label.lower() in text
    return sum(1 for w in words if w in text) >= max(1, len(words) // 2)


def _build_grading_prompt(*, prompt: str, answer: str, key_points: list[KeyPoint]) -> str:
    """Compose the grader instruction.

    Asks for coverage of specific points rather than a holistic mark, because
    a coverage vector is what the learner can argue with and what the
    scheduler can use.
    """
    listed = "\n".join(
        f"{i}. [{'required' if p.required else 'optional'}] {p.label}"
        for i, p in enumerate(key_points, 1)
    )
    return (
        "You are grading a spaced-repetition recall answer. Judge only whether the "
        "answer COVERS each key point in substance. Ignore wording, style, and length. "
        "Do not reward information that is not among the key points.\n\n"
        f"QUESTION:\n{prompt}\n\n"
        f"KEY POINTS:\n{listed}\n\n"
        f"LEARNER ANSWER:\n{answer}\n\n"
        'Reply with ONLY a JSON object: {"covered": [<numbers of covered points>], '
        '"explanation": "<one or two sentences, addressed to the learner>"}'
    )


def _parse_grade(stdout: str, key_points: list[KeyPoint]) -> GradeResult | None:
    """Parse the grader's JSON reply, tolerating surrounding prose."""
    text = (stdout or "").strip()
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        return None
    try:
        payload = json.loads(text[start : end + 1])
        covered_raw = payload.get("covered", [])
        covered = {int(n) for n in covered_raw}
    except (json.JSONDecodeError, TypeError, ValueError):
        return None

    required_indexes = {i for i, p in enumerate(key_points, 1) if p.required}
    if not required_indexes:
        score = 1.0 if covered else 0.0
    else:
        score = len(covered & required_indexes) / len(required_indexes)
    missed = [
        key_points[i - 1].label for i in sorted(required_indexes - covered) if i <= len(key_points)
    ]
    explanation = str(payload.get("explanation") or "").strip() or (
        f"Covered {len(covered & required_indexes)} of {len(required_indexes)} required points."
    )
    return GradeResult(
        score=score,
        passed=score >= 0.6,
        explanation=explanation,
        detail={"grader": "claude-code", "covered": sorted(covered), "missed": missed},
    )


__all__ = [
    "ClaudeCodeGrader",
    "IdeaGrader",
    "KeyPoint",
    "KeywordCoverageGrader",
    "grade_idea_answer",
]
